### ISSUE TITLE
Hardcoded UAV numbers for real world are used in simulation too

### ISSUE THREAD

**Issue by ViktorWalter** [ctu-mrs/summer-school-2022#1]
https://github.com/ctu-mrs/summer-school-2022/blob/58ceb91652597361ea259bffe3c8971869290c1f/mrim_task/mrim_manager/launch/manager.launch#L35
https://github.com/ctu-mrs/summer-school-2022/blob/58ceb91652597361ea259bffe3c8971869290c1f/mrim_task/mrim_manager/launch/manager.launch#L37
^ In these two lines we have hard-coded UAV numbers 47 and 7 - I'm assuming we'll be using them in RW testing.
However, this launch file is included in https://github.com/ctu-mrs/summer-school-2022/blob/58ceb91652597361ea259bffe3c8971869290c1f/mrim_task/mrim_planner/launch/planner.launch , so these numbers are expected to provide UAV state in simulation as well. 
Because of this, the default `mrim_planner` crashes a short while after takeoff, since the stored UAV states are read out as the initial `None`.

**Comment by klaxalk** [comment]
Great! Pavel broke it in the heat of preparations. Working on it.

**Comment by klaxalk** [comment]
I reverted the changes, it should work now.

**Comment by ViktorWalter** [comment]
Can confirm. It works now.
