### ISSUE TITLE
Python Virtual environment

### ISSUE THREAD

**Issue by Zartris** [ctu-mrs/summer-school-2022#14]
Hi

I think there is missing a section in the description on:
- What python libraries are allowed to be used, if we may add new libraries, and how to do this.
- What python version should be used?

In order for lint to work in pycharm we need to set the interpreter with the correct packages.

**Comment by klaxalk** [comment]
Good points:
* You can only use the libraries already present in the Singularity container. We installed some might-be-useful libraries, such as _klampt tsp openpathsampling kmeans dart scipy numpy pandas moveit pcl robotics matplotlib sklearn dubins scikit-spatial toppra sklearn_. Besides this, you could also place your own python libraries in the mrim_planner package.
* We run in Python 3.8
* Set the interpreter manually to /usr/bin/python3.8
